print("Welcome to your Adventure Story Simulator.")
print ()
print("I am going to ask you a bunch of questions and then create an epic story with you as the star.")

print()
name = input("What is your name? ")
print()
enemyName = input("What is your worst enemy's name? ")
print()
superPower = input("What is your superpower? ")
print()
live = input("Where do you live? ")
print()
food = input("What is your favorite food? ")
print()
print("\033[32m", "Hello", name,"!!!", "\033[0m", "Your ability to", "\033[36m", superPower, "\033[0m", "will make sure you never have to look at", "\033[31m", enemyName, "\033[0m", "again.", "Go eat", "\033[33m", food, "\033[0m", "as you walk down the streets of", "\033[35m", live, "\033[0m", "and use", "\033[36m", superPower,"\033[0m", "\033[34m", "for good and not evil!")
